version: '3.8'
services:
  php:
    image: 'webdevops/php-nginx:8.2-alpine'
    working_dir: /var/www
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/opt/docker/etc/nginx/vhost.conf
      - ./docker/ssl.conf:/opt/docker/etc/nginx/vhost.ssl.conf
      - ./docker/queue-worker.conf:/opt/docker/etc/supervisor.d/queue-worker.conf
      - ./docker/scheduler.sh:/opt/docker/bin/service.d/cron.d/scheduler.sh
      - app_storage:/var/www/storage:rw
      - certbot-public:/var/www/certbot:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_storage:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s

  certbot:
    image: certbot/certbot
    container_name: "codewithkyrian_certbot"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-public:/var/www/public:rw
    depends_on:
      - backend
    command: certonly --webroot --webroot-path=/var/www/public --email kyrianobikwelu@gmail.com --agree-tos --no-eff-email --force-renewal -d codewithkyrian.com  -d www.codewithkyrian.com -d backend.codewithkyrian.com

networks:
  app_network:
    driver: bridge

volumes:
  app_storage:
  mysql_storage:
  certbot-public:
  certbot-etc:
  certbot-var:
